baseURL = 'https://blog.snapnetwork.io/'
languageCode = 'en-us'
title = 'SNAP Network'
theme = "github-style"

[params]
author = "SNAP Network"
github = "RedeemProtocol"
url = "https://www.snapnetwork.io"
keywords = "SNAP Network, Blockchain, Web3"
